### ISSUE TITLE
Guard sometimes quit when a file is deleted

### ISSUE THREAD

**Issue by rymai** [guard/guard#1]
Hi,

Guard was running and I ran a task that delete some files, then Guard ended-up because it couldn't find the deleted file anymore (as I understand it).

Following is the dump of the error stack which lead to the crash:

```
/Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:52:in `mtime': No such file or directory - /Users/remy/path_to_a_deleted_file (Errno::ENOENT)
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:52:in `recent_file?'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:43:in `block in modified_files'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:43:in `select'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:43:in `modified_files'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:35:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/interactor.rb:7:in `block in init_signal_traps'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:32:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:32:in `eof?'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:32:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/interactor.rb:7:in `block in init_signal_traps'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:32:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:32:in `eof?'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:32:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:44:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:22:in `block in start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `call'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:37:in `watch_change'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/listener.rb:22:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard.rb:32:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/lib/guard/cli.rb:11:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/thor-0.14.3/lib/thor/task.rb:22:in `run'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/thor-0.14.3/lib/thor/invocation.rb:118:in `invoke_task'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/thor-0.14.3/lib/thor.rb:246:in `dispatch'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/thor-0.14.3/lib/thor/base.rb:389:in `start'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/gems/guard-0.1.0.beta.1/bin/guard:6:in `<top (required)>'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/bin/guard:19:in `load'
    from /Users/remy/.rvm/gems/ruby-1.9.2-p0/bin/guard:19:in `<main>'
```

**Comment by poetchou** [comment]
placeholder-guard
