### ISSUE TITLE
Installing fails (missing hitimes)

### ISSUE THREAD

**Issue by ghost** [guard/guard#624]
Hi there. I run into some problems while trying to install guard: Running `bundle` on a Gemfile described in the Installation Howto i get

```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.0 extconf.rb 
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h


Gem files will remain installed in /tmp/andi/bundler20140911-16499-rxe2yl/hitimes-1.2.2/gems/hitimes-1.2.2 for inspection.
Results logged to /tmp/andi/bundler20140911-16499-rxe2yl/hitimes-1.2.2/gems/hitimes-1.2.2/ext/hitimes/c/gem_make.out
An error occurred while installing hitimes (1.2.2), and Bundler cannot continue.
Make sure that `gem install hitimes -v '1.2.2'` succeeds before bundling.
```

But `hitimes` is already installed:

```
$ gem list hitimes
*** LOCAL GEMS ***
hitimes (1.2.2)
```

What seems strange to me is that on my system (Debian testing (jessie)) the file `/usr/lib/ruby/include/ruby.h` doesn't exist. In the existing folder `/usr/lib/ruby` i created `include/ruby.h` which links to either

```
/usr/include/ruby-2.1.0/ruby.h
/usr/include/ruby-2.1.0/ruby/ruby.h
```

which are the only `ruby.h` files on my system. Trying `bundle` again yields

```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.0 extconf.rb 
checking for clock_gettime() in -lrt... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/ruby2.0
    --with-rtlib
    --without-rtlib
/usr/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /usr/lib/ruby/2.0.0/mkmf.rb:519:in `try_link0'
    from /usr/lib/ruby/2.0.0/mkmf.rb:534:in `try_link'
    from /usr/lib/ruby/2.0.0/mkmf.rb:720:in `try_func'
    from /usr/lib/ruby/2.0.0/mkmf.rb:950:in `block in have_library'
    from /usr/lib/ruby/2.0.0/mkmf.rb:895:in `block in checking_for'
    from /usr/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
    from /usr/lib/ruby/2.0.0/mkmf.rb:310:in `open'
    from /usr/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
    from /usr/lib/ruby/2.0.0/mkmf.rb:310:in `open'
    from /usr/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
    from /usr/lib/ruby/2.0.0/mkmf.rb:894:in `checking_for'
    from /usr/lib/ruby/2.0.0/mkmf.rb:945:in `have_library'
    from extconf.rb:10:in `<main>'


Gem files will remain installed in /tmp/andi/bundler20140911-30648-1ns0lcv/hitimes-1.2.2/gems/hitimes-1.2.2 for inspection.
Results logged to /tmp/andi/bundler20140911-30648-1ns0lcv/hitimes-1.2.2/gems/hitimes-1.2.2/ext/hitimes/c/gem_make.out
An error occurred while installing hitimes (1.2.2), and Bundler cannot continue.
Make sure that `gem install hitimes -v '1.2.2'` succeeds before bundling.
```

I've already installed `build-essential`,`ruby-dev` and `ruby2.1-dev`, there is no  `ruby2.0-dev` available for my installation, [only for the unstable tree](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=ruby2.0-dev).
Further environment:

```
$ ruby -e 'puts RUBY_DESCRIPTION'
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
$ gem -v
2.2.2
```

Any suggestions welcome!

**Comment by sreusr** [comment]
doesn't work on raspbian jessie :(
