### ISSUE TITLE
Invalid no. of arguments for notification in DSL reader

### ISSUE THREAD

**Issue by mintuhouse** [guard/guard#765]
I get the following error when I run
```` guard init rspec ```
Most likely because the method [notification](https://github.com/guard/guard/blob/master/lib/guard/dsl_reader.rb#L18) doesn't use the same no. of arguments as original
```
gems/guard-2.12.5/lib/guard/dsl.rb:383:in `rescue in evaluate': Invalid Guardfile, original error is: 

wrong number of arguments (1 for 0), 
backtrace: 
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl_reader.rb:18:in `notification'
	(dsl)> ./Guardfile:109:in `evaluate'
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl.rb:377:in `instance_eval'
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl.rb:377:in `evaluate'
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/guardfile/evaluator.rb:110:in `guardfile_include?'
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/plugin_util.rb:133:in `add_to_guardfile'
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/guardfile/generator.rb:72:in `initialize_template'
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/cli/environments/valid.rb:49:in `block in initialize_guardfile'
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/cli/environments/valid.rb:48:in `each'
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/cli/environments/valid.rb:48:in `initialize_guardfile'
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/cli.rb:174:in `init'
	(dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	(dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	(dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	(dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/aruba_adapter.rb:32:in `execute'
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/aruba_adapter.rb:19:in `execute!'
	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/bin/_guard-core:11:in `<main>' (Guard::Dsl::Error)

```

**Comment by e2** [comment]
Thanks for reporting this!

The newer DSL reader is actually quite buggy - should be fixed soon.
