### ISSUE TITLE
Trouble with implementing an Inline Guard

### ISSUE THREAD

**Issue by radavis** [guard/guard#767]
I've done my best to follow the [instructions for building an inline guard](https://github.com/guard/guard/wiki/Create-a-guard#inline-guard), but I'm not having much luck.

```
# guard/video.rb
require "guard/compat/plugin"

module ::Guard
  class Video < Plugin
    def initialize(options = {})
    end

    def run_on_additions(paths)
      paths.each do |path|
        puts "A new file was detected: #{path}"
      end
    end
  end
end
```

```
# Gemfile

source "https://rubygems.org"

ruby "2.2.2"

gem "guard"
gem "guard-compat"
```

```
# Guardfile

require './guard/video'

guard :video do
  watch(%r{^screencasts/.+\.mov$})
end

```

```
$bundle exec guard
/Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/internals/plugins.rb:45:in `block (2 levels) in matcher_for': undefined method `name' for nil:NilClass (NoMethodError)
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/internals/plugins.rb:40:in `each'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/internals/plugins.rb:40:in `all?'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/internals/plugins.rb:40:in `block in matcher_for'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/internals/plugins.rb:16:in `call'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/internals/plugins.rb:16:in `block in all'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/internals/plugins.rb:16:in `select'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/internals/plugins.rb:16:in `all'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/internals/scope.rb:45:in `block in grouped_plugins'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/internals/scope.rb:39:in `map'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/internals/scope.rb:39:in `grouped_plugins'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/runner.rb:19:in `block in run'
	from /Users/rd/.gem/ruby/2.2.2/gems/lumberjack-1.0.9/lib/lumberjack.rb:32:in `unit_of_work'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/runner.rb:18:in `run'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/commander.rb:34:in `start'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/cli/environments/valid.rb:16:in `start_guard'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/cli.rb:122:in `start'
	from /Users/rd/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/rd/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/rd/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/rd/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/aruba_adapter.rb:32:in `execute'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/lib/guard/aruba_adapter.rb:19:in `execute!'
	from /Users/rd/.gem/ruby/2.2.2/gems/guard-2.12.6/bin/_guard-core:11:in `<main>'
```

**Comment by radavis** [comment]
Missing a call to `super` in my initializer.

**Comment by e2** [comment]
I improved the wiki page - inheritance is generally evil, but with so many guard plugins out there, the cat is out of the bag.
