### ISSUE TITLE
guard crashing on load, not sure why.

### ISSUE THREAD

**Issue by jms1989** [guard/guard#806]
I have a issue with guard not working for some unknown reason. This is a fresh server, I couldn't get anything to work until I upgraded to the latest version of ruby and now guard doesn't work and I'm not sure why. I started with the distro default, ruby 2.0.0 but even bundler would error on some gem.

OS: centos 7
ruby 2.2.3p173
gem 2.4.8
guard 2.13

error
```ruby
07:37:16 - ERROR - Invalid Guardfile, original error is:
> [#]
> [#] cannot load such file -- guard/guard,
> [#] backtrace:
> [#]   (dsl)> ./Guardfile:1:in `require'
> [#]   (dsl)> ./Guardfile:1:in `evaluate'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/dsl.rb:377:in `instance_eval'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/dsl.rb:377:in `evaluate'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/guardfile/evaluator.rb:91:in `evaluate'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard.rb:134:in `_evaluate'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard.rb:49:in `setup'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/commander.rb:32:in `start'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/cli.rb:122:in `start'
> [#]   (dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#]   (dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#]   (dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#]   (dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:32:in `execute'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#]   (dsl)> $GEM_PATH[0]/gems/guard-2.13.0/bin/_guard-core:11:in `<main>'
```

**Comment by e2** [comment]
One of your guard plugins is outdated - the one probably appearing in your Guardfile.

Attach your Guardfile here if you're unsure.

**Comment by jms1989** [comment]
Guardfile
```
require 'guard/guard'

module ::Guard
  class LessWatcher < ::Guard::Guard

    def start
      run_on_changes([])
    end

    def reload
      start
      stop
    end

    # Default behaviour on file(s) changes that the Guard plugin watches.
    # @param [Array<String>] paths the changes files or paths
    # @raise [:task_has_failed] when run_on_change has failed
    # @return [Object] the task result
    #
    def run_on_changes(paths)
      dest_path = "source/stylesheets/application.css.less"
      return if paths == [dest_path]

      new_number = if File.exists?(dest_path)
                     contents = File.read(dest_path)
                     if contents =~ %r{// (\d+)}
                       $1.to_i + 1
                     end
                   end

      new_number = new_number.to_i

      template = File.read("source/stylesheets/application-template.css.less")

      File.open(dest_path, 'w') do |file|
        file.write(template.gsub(%r{// (\d+)}) { "// #{new_number}"})
      end
    end
  end
end

guard :less_watcher do
  watch(%r{^source/stylesheets/(.+)\.less$})
end
```

**Comment by e2** [comment]
The way you inline Guards has changed.

Here's an example from the wiki: https://github.com/guard/guard/wiki/Hooks-and-callbacks#notes--caveats

This means:

1. you don't need the `require` at all
2. the base class should not be `::Guard::Guard` but `Plugin`
3. You probably want `run_on_modifications` instead of `run_on_changes`

And then it should work.

**Comment by jms1989** [comment]
Brilliant. Thank you!
