### ISSUE TITLE
Options in cmd:

### ISSUE THREAD

**Issue by rokka-n** [guard/guard#818]
Hi,

How to disable all additional options that guard inserting into rspec runs?

```
guard :rspec, cmd: 'rspec' do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec" }
end
```

bundle rspec runs the tests. But with guard - rspec runs fails.
It runs this long list of options, which were not specified anywhere? Specifically it's formatters.

rspec -f documentation -r .rvm/gems/ruby-2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec_formatter.rb -f Guard::RSpecFormatter --failure-exit-code 2  spec

```
bundle exec guard --debug22:31:20 - DEBUG - Notiffany: gntp not available (Please add "gem 'ruby_gntp'" to your Gemfile and run your app with "bundle exec".).
22:31:20 - DEBUG - Notiffany: growl not available (Please add "gem 'growl'" to your Gemfile and run your app with "bundle exec".).
22:31:20 - DEBUG - Notiffany: terminal_notifier not available (Please add "gem 'terminal-notifier-guard'" to your Gemfile and run your app with "bundle exec".).
22:31:20 - DEBUG - Notiffany: libnotify not available (Unsupported platform "darwin13.4.0").
22:31:20 - DEBUG - Notiffany: notifysend not available (Unsupported platform "darwin13.4.0").
22:31:20 - DEBUG - Notiffany: notifu not available (Unsupported platform "darwin13.4.0").
22:31:20 - DEBUG - Command execution: {"ALTERNATE_EDITOR"=>"false"} emacsclient --eval '1'
22:31:20 - DEBUG - Notiffany: emacs not available (Emacs client failed).
22:31:20 - DEBUG - Notiffany: tmux not available (:tmux notifier is only available inside a TMux session.).
22:31:20 - DEBUG - Notiffany: file not available (No :path option given).
22:31:20 - DEBUG - Notiffany is using TerminalTitle to send notifications.
22:31:20 - DEBUG - Command execution: hash stty
22:31:20 - DEBUG - Guard starts all plugins
22:31:20 - DEBUG - Hook :start_begin executed for Guard::RSpec
22:31:20 - INFO - Guard::RSpec is running
22:31:20 - DEBUG - Hook :start_end executed for Guard::RSpec
22:31:21 - INFO - Guard is now watching at 's3uploader'
22:31:21 - DEBUG - Start interactor
22:31:21 - DEBUG - Command execution: stty -g 2>/dev/null
[1] guard(main)>
22:31:22 - DEBUG - Interactor was stopped or killed
22:31:22 - DEBUG - Command execution: stty  2>/dev/null
22:31:22 - INFO - Run all
22:31:22 - DEBUG - Hook :run_all_begin executed for Guard::RSpec
22:31:22 - INFO - Running all specs

COVERAGE:  54.29% -- 19/35 lines in 2 files

+----------+-------------------+-------+--------+-----------------------------------------------+
| coverage | file              | lines | missed | missing                                       |
+----------+-------------------+-------+--------+-----------------------------------------------+
|  51.52%  | lib/s3uploader.rb | 33    | 16     | 18, 22-23, 28, 30-33, 36-38, 40-41, 45-46, 54 |
+----------+-------------------+-------+--------+-----------------------------------------------+
1 file(s) with 100% coverage not shown
s3uploader/lib/s3uploader.rb:17:in `getargs': invalid option: -r (OptionParser::InvalidOption)
	from s3uploader/lib/s3uploader.rb:53:in `<top (required)>'
	from s3uploader/spec/spec_helper.rb:2:in `require'
	from s3uploader/spec/spec_helper.rb:2:in `<top (required)>'
	from s3uploader/spec/s3uploader_spec.rb:8:in `require'
	from s3uploader/spec/s3uploader_spec.rb:8:in `<top (required)>'
	from core/configuration.rb:1361:in `load'
	from .rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from .rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1359:in `each'
	from .rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from .rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:106:in `setup'
	from .rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:92:in `run'
	from .rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:78:in `run'
	from .rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:45:in `invoke'
	from .rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.2/exe/rspec:4:in `<top (required)>'
	from .rvm/gems/ruby-2.3.0/bin/rspec:22:in `load'
	from .rvm/gems/ruby-2.3.0/bin/rspec:22:in `<main>'
	from .rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from .rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
22:31:22 - ERROR - Failed: "rspec -f documentation -r .rvm/gems/ruby-2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec_formatter.rb -f Guard::RSpecFormatter --failure-exit-code 2  spec" (exit code: 1)

22:31:22 - DEBUG - Start interactor
22:31:22 - DEBUG - Command execution: stty -g 2>/dev/null
```

**Comment by e2** [comment]
You shouldn't disable those options, because they're necessary.

Instead, you should use RSpec to stub out `ARGV`. 

I'm guessing that's what `OptionParser` in `s3uploader/lib/s3uploader.rb` is using.

You probably have a line like: 

```ruby
opts.parse! ARGV
```

see: http://www.relishapp.com/rspec/rspec-mocks/v/3-4/docs/mutating-constants/stub-defined-constant

e.g.

```ruby
stub_const("ARGV", ['foo.txt', 's3://foo/bar/baz'])
```

**Comment by rokka-n** [comment]
Thank you!
