### ISSUE TITLE
Guard errors and dies when trying to use --listen-on

### ISSUE THREAD

**Issue by jkugler** [guard/guard#906]
In trying to use listen on, I specify this on the command line, per https://github.com/guard/guard/wiki/Command-line-options-for-Guard#running-guard-in-a-vm
```
bin/guard --listen-on '10.0.2.2:4000' -w /path/to/my/source
```
But that dies right away with
```
/var/lib/gems/2.3.0/gems/guard-2.14.2/lib/guard.rb:53:in `setup': undefined method `on' for Listen:Module (NoMethodError)
        from /var/lib/gems/2.3.0/gems/guard-2.14.2/lib/guard/commander.rb:32:in `start'
        from /var/lib/gems/2.3.0/gems/guard-2.14.2/lib/guard/cli/environments/valid.rb:16:in `start_guard'
        from /var/lib/gems/2.3.0/gems/guard-2.14.2/lib/guard/cli.rb:122:in `start'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /var/lib/gems/2.3.0/gems/guard-2.14.2/lib/guard/aruba_adapter.rb:32:in `execute'
        from /var/lib/gems/2.3.0/gems/guard-2.14.2/lib/guard/aruba_adapter.rb:19:in `execute!'
        from /var/lib/gems/2.3.0/gems/guard-2.14.2/bin/_guard-core:11:in `<main>'

```
This is guard 2.14.2

**Comment by rymai** [comment]
TCP support has been removed from Listen starting with Listen 3.0 (https://github.com/guard/listen/issues/319), the wiki is outdated, I'll fix that.

There seem to be a workaround for that, see https://github.com/guard/listen/issues/258#issuecomment-222924196

I'm closing this issue now, and will update the wiki to point to the workaround.

Thanks for raising the issue!
