### ISSUE TITLE
Rails 5.2 compatibilty?

### ISSUE THREAD

**Issue by nickmjones** [guard/guard#908]
I'm trying to use guard-puma in a Rails 5.2 project with Puma 3.11 as the (now default) server. Upon running either `guard start` or `bundle exec guard`, Guard jumps into a Traceback(with `--debug`):

```12:00:16 - DEBUG - Notiffany: gntp not available (Please add "gem 'ruby_gntp'" to your Gemfile and run your app with "bundle exec".).
12:00:16 - DEBUG - Notiffany: growl not available (Please add "gem 'growl'" to your Gemfile and run your app with "bundle exec".).
12:00:16 - DEBUG - Notiffany: terminal_notifier not available (Please add "gem 'terminal-notifier-guard'" to your Gemfile and run your app with "bundle exec".).
12:00:16 - DEBUG - Notiffany: libnotify not available (Unsupported platform "darwin17.5.0").
12:00:16 - DEBUG - Notiffany: notifysend not available (Unsupported platform "darwin17.5.0").
12:00:16 - DEBUG - Notiffany: notifu not available (Unsupported platform "darwin17.5.0").
12:00:16 - DEBUG - Command execution: {"ALTERNATE_EDITOR"=>"false"} emacsclient --eval '1'
12:00:16 - DEBUG - Notiffany: tmux not available (:tmux notifier is only available inside a TMux session.).
12:00:16 - DEBUG - Notiffany: file not available (No :path option given).
12:00:16 - DEBUG - Command execution: {"ALTERNATE_EDITOR"=>"false"} emacsclient --eval '1'
12:00:16 - DEBUG - Notiffany is using Emacs to send notifications.
12:00:16 - DEBUG - Notiffany is using TerminalTitle to send notifications.
12:00:16 - DEBUG - Command execution: hash stty
12:00:16 - DEBUG - Guard starts all plugins
12:00:16 - DEBUG - Hook :start_begin executed for Guard::LiveReload
12:00:16 - DEBUG - Hook :start_end executed for Guard::LiveReload
12:00:16 - INFO - LiveReload is waiting for a browser to connect.
12:00:16 - DEBUG - Hook :start_begin executed for Guard::Puma
12:00:16 - INFO - Puma starting on port 4000 in development environment.
12:00:16 - DEBUG - Command execution: sh -c 'cd /Users/nick.jones/code/leads && puma --config  --control-token e6e6585cd977de7a9e7051255cc9 --control tcp://localhost:9293 --port 4000 --environment development --quiet  &'
12:00:16 - DEBUG - Hook :start_end executed for Guard::Puma
12:00:16 - INFO - Guard is now watching at '/Users/nick.jones/code/leads'
12:00:16 - DEBUG - Start interactor
12:00:16 - DEBUG - Command execution: stty -g 2>/dev/null
[1] guard(main)> Traceback (most recent call last):
        11: from /usr/local/opt/rbenv/versions/2.5.0/bin/puma:23:in `<main>'
        10: from /usr/local/opt/rbenv/versions/2.5.0/bin/puma:23:in `load'
         9: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/bin/puma:8:in `<top (required)>'
         8: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/bin/puma:8:in `new'
         7: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/cli.rb:69:in `initialize'
         6: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/cli.rb:69:in `new'
         5: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/launcher.rb:59:in `initialize'
         4: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:192:in `load'
         3: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:192:in `each'
         2: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:192:in `block in load'
         1: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/dsl.rb:41:in `_load_from'
/usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/dsl.rb:41:in `read': No such file or directory @ rb_sysopen - --control-token (Errno::ENOENT)

```

My Gemfile looks like this:

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.0'
gem 'rails', '~> 5.2.0'
gem 'pg'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'bourbon'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'guard'
  gem 'guard-puma'
  gem 'guard-livereload'
end

group :test do
  gem 'capybara', '>= 2.15', '< 4.0'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
end

```

Running `rails s` starts Puma as normal, which is what leads me to believe this may be a compatibility issue with Guard and 5.2?

**Comment by matoakley** [comment]
This issue is related to the `guard-puma` plugin rather than Guard itself. I have run into the same issue and been able to find a work-around until the plugin can be updated. See [https://github.com/jc00ke/guard-puma/issues/36](https://github.com/jc00ke/guard-puma/issues/36) for solution.

**Comment by rymai** [comment]
Thanks @matoakley, closing since it's a `guard-puma` issue.
