### ISSUE TITLE
Guard complains about missing gem; extensions not built

### ISSUE THREAD

**Issue by jaredmoody** [guard/guard#909]
When starting guard I'm seeing lots of output like this:

```
Ignoring byebug-9.0.6 because its extensions are not built.  Try: gem pristine byebug --version 9.0.6
```

and

```
/Users/jaredmoody/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find nokogiri-1.8.3 in any of the sources (Bundler::GemNotFound)
	from /Users/jaredmoody/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler/spec_set.rb:85:in `map!'
	from /Users/jaredmoody/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler/spec_set.rb:85:in `materialize'
	from /Users/jaredmoody/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler/definition.rb:171:in `specs'
	from /Users/jaredmoody/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler/definition.rb:238:in `specs_for'
	from /Users/jaredmoody/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler/definition.rb:227:in `requested_specs'
	from /Users/jaredmoody/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler/runtime.rb:108:in `block in definition_method'
	from /Users/jaredmoody/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler/runtime.rb:20:in `setup'
	from /Users/jaredmoody/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler.rb:107:in `setup'
	from /Users/jaredmoody/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler/setup.rb:20:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

running `gem pristine byebug --version 9.0.6` does not change anything, and in this example, nokogiri 1.8.3 is in my bundle:

```
> bundle list nokogiri
/Users/jaredmoody/.gem/ruby/2.3.7/gems/nokogiri-1.8.3
```

I commented out my entire Guardfile and the output is the same. 

Can someone point me in the right direction here? Thanks!

**Comment by jaredmoody** [comment]
I resolved this after cleaning up all the gems in all the rubies on my system, still curious why this only affected guard, but closing.
