### ISSUE TITLE
uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState

### ISSUE THREAD

**Issue by franklinjosmell** [guard/guard#978]
I'm updating a rails app to Rails 7 and I get the following:

```
16:40:33 - ERROR - Invalid Guardfile, original error is:
> [#]
> [#] uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState
> [#]
> [#]         IsolatedExecutionState[:xml_mini_backend]
> [#]         ^^^^^^^^^^^^^^^^^^^^^^,
> [#] backtrace:
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:184:in `current_thread_backend'
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:103:in `backend='
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:11:in `<top (required)>'
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `require'
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/duration.rb:3:in `require'
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/duration.rb:3:in `<top (required)>'
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/time/calculations.rb:3:in `require'
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/string/conversions.rb:4:in `require'
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/string/conversions.rb:4:in `<top (required)>'
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/string.rb:3:in `require'
> [#] 	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/string.rb:3:in `<top (required)>'
> [#] 	(dsl)> ./Guardfile:1:in `require'
> [#] 	(dsl)> ./Guardfile:1:in `evaluate'
> [#] 	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/dsl.rb:381:in `instance_eval'
> [#] 	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/dsl.rb:381:in `evaluate'
> [#] 	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/guardfile/evaluator.rb:85:in `evaluate'
> [#] 	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard.rb:135:in `_evaluate'
> [#] 	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard.rb:50:in `setup'
> [#] 	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/commander.rb:34:in `start'
> [#] 	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/cli/environments/valid.rb:18:in `start_guard'
> [#] 	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/cli.rb:124:in `start'
> [#] 	(dsl)> $GEM_HOME/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
> [#] 	(dsl)> $GEM_HOME/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
> [#] 	(dsl)> $GEM_HOME/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
> [#] 	(dsl)> $GEM_HOME/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
> [#] 	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/aruba_adapter.rb:34:in `execute'
> [#] 	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/aruba_adapter.rb:21:in `execute!'
> [#] 	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/bin/_guard-core:12:in `<main>'
/Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/dsl.rb:387:in `rescue in evaluate': Invalid Guardfile, original error is:  (Guard::Dsl::Error)

uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState

        IsolatedExecutionState[:xml_mini_backend]
        ^^^^^^^^^^^^^^^^^^^^^^,
backtrace:
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:184:in `current_thread_backend'
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:103:in `backend='
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:11:in `<top (required)>'
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `require'
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/duration.rb:3:in `require'
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/duration.rb:3:in `<top (required)>'
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/time/calculations.rb:3:in `require'
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/string/conversions.rb:4:in `require'
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/string/conversions.rb:4:in `<top (required)>'
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/string.rb:3:in `require'
	(dsl)> $GEM_HOME/gems/activesupport-7.0.1/lib/active_support/core_ext/string.rb:3:in `<top (required)>'
	(dsl)> ./Guardfile:1:in `require'
	(dsl)> ./Guardfile:1:in `evaluate'
	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/dsl.rb:381:in `instance_eval'
	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/dsl.rb:381:in `evaluate'
	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/guardfile/evaluator.rb:85:in `evaluate'
	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard.rb:135:in `_evaluate'
	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard.rb:50:in `setup'
	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/commander.rb:34:in `start'
	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/cli/environments/valid.rb:18:in `start_guard'
	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/cli.rb:124:in `start'
	(dsl)> $GEM_HOME/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	(dsl)> $GEM_HOME/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	(dsl)> $GEM_HOME/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	(dsl)> $GEM_HOME/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/aruba_adapter.rb:34:in `execute'
	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/lib/guard/aruba_adapter.rb:21:in `execute!'
	(dsl)> $GEM_HOME/bundler/gems/guard-b92fabf2802b/bin/_guard-core:12:in `<main>'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/dsl.rb:380:in `evaluate'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/guardfile/evaluator.rb:85:in `evaluate'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard.rb:135:in `_evaluate'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard.rb:50:in `setup'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/commander.rb:34:in `start'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/cli/environments/valid.rb:18:in `start_guard'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/cli.rb:124:in `start'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/aruba_adapter.rb:34:in `execute'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/aruba_adapter.rb:21:in `execute!'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/bin/_guard-core:12:in `<main>'
/Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)

        IsolatedExecutionState[:xml_mini_backend]
        ^^^^^^^^^^^^^^^^^^^^^^
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:103:in `backend='
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:11:in `<top (required)>'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `require'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/duration.rb:3:in `require'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/duration.rb:3:in `<top (required)>'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/time/calculations.rb:3:in `require'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/string/conversions.rb:4:in `require'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/string/conversions.rb:4:in `<top (required)>'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/string.rb:3:in `require'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/core_ext/string.rb:3:in `<top (required)>'
	from /Users/franklinticona/repos/apps/microblog/Guardfile:1:in `require'
	from /Users/franklinticona/repos/apps/microblog/Guardfile:1:in `evaluate'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/dsl.rb:381:in `instance_eval'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/dsl.rb:381:in `evaluate'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/guardfile/evaluator.rb:85:in `evaluate'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard.rb:135:in `_evaluate'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard.rb:50:in `setup'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/commander.rb:34:in `start'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/cli/environments/valid.rb:18:in `start_guard'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/cli.rb:124:in `start'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/aruba_adapter.rb:34:in `execute'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/lib/guard/aruba_adapter.rb:21:in `execute!'
	from /Users/franklinticona/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bundler/gems/guard-b92fabf2802b/bin/_guard-core:12:in `<main>'
```

The problem seems to be due to ActiveSupport from Rails 7, since I have tried different versions of ruby with Rails 6 and everything works fine.

One possible solution I found is 

`require "active_support/isolated_execution_state"`

Would it be the correct solution? If so, in which file would it be better to put it.

**Comment by rymai** [comment]
@franklinjosmell Could you please share your `Guardfile`?

**Comment by franklinjosmell** [comment]
Hi Rémy, this is the content of my Guardfile

```
require "active_support/core_ext/string"

# Defines the matching rules for Guard.
guard :minitest, spring: "bin/rails test", all_on_start: false do
  watch(%r{^test/(.*)/?(.*)_test\.rb$})
  watch("test/test_helper.rb") { "test" }
  watch("config/routes.rb") { interface_tests }
  watch(%r{app/views/layouts/*}) { interface_tests }
  watch(%r{^app/models/(.*?)\.rb$}) do |matches|
    "test/models/#{matches[1]}_test.rb"
  end
  watch(%r{^test/fixtures/(.*?)\.yml$}) do |matches|
    "test/models/#{matches[1].singularize}_test.rb"
  end
  watch(%r{^app/mailers/(.*?)\.rb$}) do |matches|
    "test/mailers/#{matches[1]}_test.rb"
  end
  watch(%r{^app/views/(.*)_mailer/.*$}) do |matches|
    "test/mailers/#{matches[1]}_mailer_test.rb"
  end
  watch(%r{^app/controllers/(.*?)_controller\.rb$}) do |matches|
    resource_tests(matches[1])
  end
  watch(%r{^app/views/([^/]*?)/.*\.html\.erb$}) do |matches|
    ["test/controllers/#{matches[1]}_controller_test.rb"] +
      integration_tests(matches[1])
  end
  watch(%r{^app/helpers/(.*?)_helper\.rb$}) do |matches|
    ["test/helpers/#{matches[1]}_helper_test.rb"] +
      integration_tests(matches[1])
  end
  watch("app/views/layouts/application.html.erb") do
    "test/integration/site_layout_test.rb"
  end
  watch("app/controllers/sessions_controller.rb") do
    ["test/controllers/sessions_controller_test.rb",
      "test/integration/users_login_test.rb"]
  end
  watch("app/controllers/account_activations_controller.rb") do
    "test/integration/users_signup_test.rb"
  end
  watch("app/controllers/users_controller.rb") do
    "test/integration/user_show_test.rb"
  end
  watch(%r{app/views/users/*}) do
    resource_tests("users") +
      ["test/integration/microposts_interface_test.rb"]
  end
  watch(%r{^app/channels/(.*?)\.rb$}) do |matches|
    "test/channels/#{matches[1]}_test.rb"
  end
  watch("app/models/connection.rb") do
    ["test/channels/appearance_channel_test.rb",
      "test/channels/application_cable/connection_test.rb"]
  end
  watch("app/models/appearance.rb") do
    "test/channels/appearance_channel_test.rb"
  end
end

# Returns the integration tests corresponding to the given resource.
def integration_tests(resource = :all)
  if resource == :all
    Dir["test/integration/*"]
  else
    Dir["test/integration/#{resource}_*.rb"]
  end
end

# Returns all tests that hit the interface.
def interface_tests
  integration_tests << "test/controllers"
end

# Returns the controller tests corresponding to the given resource.
def controller_test(resource)
  "test/controllers/#{resource}_controller_test.rb"
end

# Returns all tests for the given resource.
def resource_tests(resource)
  integration_tests(resource) << controller_test(resource)
end
```

**Comment by rymai** [comment]
Thanks! What happens if you comment the first line (`require "active_support/core_ext/string"`)?

**Comment by franklinjosmell** [comment]
@rymai If I comment that line everything is fine! Many thanks!

**Comment by rymai** [comment]
Should we close the issue?

**Comment by franklinjosmell** [comment]
Done! thanks for your time

**Comment by franklinjosmell** [comment]
Done! thanks for your time

**Comment by rymai** [comment]
No worries, thanks!
