### ISSUE TITLE
lib/guard/jobs/pry_wrapper.rb:294:in `initialize': wrong number of arguments (given 3, expected 0) (ArgumentError)

### ISSUE THREAD

**Issue by nfedyashev** [guard/guard#980]
Looks like I've just found a bug. Let me know if any additional info is needed

```
bundle exec guard

17:57:35 - INFO - Bye bye...
/home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard/jobs/pry_wrapper.rb:294:in `initialize': wrong number of arguments (given 3, expected 0) (ArgumentError)
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard/jobs/pry_wrapper.rb:294:in `new'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard/jobs/pry_wrapper.rb:294:in `_configure_prompt'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard/jobs/pry_wrapper.rb:161:in `_setup'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard/jobs/pry_wrapper.rb:78:in `initialize'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard/interactor.rb:17:in `new'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard/interactor.rb:17:in `initialize'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard.rb:67:in `new'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard.rb:67:in `setup'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard/commander.rb:32:in `start'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard/cli/environments/valid.rb:16:in `start_guard'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard/cli.rb:122:in `start'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard/aruba_adapter.rb:32:in `execute'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/lib/guard/aruba_adapter.rb:19:in `execute!'
from /home/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/guard-2.17.0/bin/_guard-core:11:in `<main>'
```

```
cat Gemfile.lock | grep guard
    guard (2.17.0)
    guard-compat (1.2.1)
    guard-rspec (4.7.3)
      guard (~> 2.1)
      guard-compat (~> 1.1)
  guard (~> 2.17)
  guard-rspec (~> 4.7)
```

```
cat Gemfile.lock  | grep pry
      pry (>= 0.9.12)
    pry (0.10.3)
    pry-nav (0.2.4)
      pry (>= 0.9.10, < 0.11.0)
    pry-rails (0.3.4)
      pry (>= 0.9.10)
  pry-nav
  pry-rails

```

Actual Guardfile is irrelevant, could be even a blank file

**Comment by rymai** [comment]
I believe the dependency constraint for Pry was bumped to `>= 0.13.0` with https://github.com/guard/guard/pull/974, and released in Guard `2.18.0` (https://github.com/guard/guard/pull/975).

Updating to Guard 2.18.0 should solve this (by updating Pry).
